# Generated by Django 4.2.11 on 2024-05-13 01:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='podcast',
            unique_together={('owner', 'title')},
        ),
    ]
