# Generated by Django 4.2.11 on 2024-05-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_podcast_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='processing_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
